version: '3.8'

services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    env_file: ./.env

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  pixelplanet:
    image: node:18
    working_dir: /app
    volumes:
      - ./pixelplanet:/app
    command: bash -c "npm install && pm2 start ecosystem.yml"
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql
    restart: always

volumes:
  redis_data:
  mysql_data:
