version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: pixelplanet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: pixelplanet_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pixelplanet
      MYSQL_USER: pixelplanet
      MYSQL_PASSWORD: sqlpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  pixelplanet:
    image: node:18
    container_name: pixelplanet_app
    working_dir: /app
    volumes:
      - ./pixelplanet:/app
    command: bash -c "npm install && pm2 start ecosystem.yml"
    environment:
      PORT: 5000
      HOST: "0.0.0.0"
      REDIS_URL: "redis://pixelplanet_redis:6379"
      MYSQL_HOST: pixelplanet_mysql
      MYSQL_USER: pixelplanet
      MYSQL_PW: sqlpassword
      MYSQL_DATABASE: pixelplanet
      SESSION_SECRET: "supersecretstring"
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
